[build]
  # Directory where the built files are located
  publish = "dist"
  
  # Command to build the project
  command = "npm run build"

# Handle Single Page Application (SPA) routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
